version: '3.5'
services:
  micro:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=db
      - DB_USERNAME=rails
      - DB_PASSWORD=password
    networks:
      database: {}
volumes:
  postgres:

networks:
  database:
    external: true